services:
  mongo:
    image: mongo:7-jammy
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network

  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-secret-key-here
      - MONGODB_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    restart: unless-stopped

  frontend:
    build: .
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongo_data:
  node_modules_backend:
  node_modules_frontend:
